---
input_data_root: /Users/simonmoulds/projects/decadal-flood-prediction/data-raw
output_data: results

observed_data:
  root: resources
  giss:
    subdirectory: observed_data/GISS
  gpcc:
    subdirectory: observed_data/GPCC
  hadcrut4:
    subdirectory: observed_data/HadCRUT4
  hadslp2r:
    subdirectory: observed_data/HadSLP2r
  hadisst:
    subdirectory: observed_data/HadISST
  ncdc:
    subdirectory: observed_data/NCDC

ensemble_data:
  root: resources
  cmip5:
    subdirectory:
      - esmvaltool_output/recipe_s20_cmip5_autogen_20221214_103843/
    grid_subdirectory:
      - esmvaltool_output/recipe_s20_grid_cmip5_autogen_20220622_133817
    models:
      - CanCM4
      - GFDL-CM2p1
      - HadCM3
      - MIROC5
      - MPI-ESM-LR
  cmip6:
    subdirectory:
      - esmvaltool_output/recipe_s20_cmip6_autogen_20221214_120531
      - ncar_prec_data/recipe1
    grid_subdirectory:
      - esmvaltool_output/recipe_s20_grid_cmip6_autogen_20220622_153338
    models:
      - CanESM5
      - CESM1-1-CAM5-CMIP5
      - EC-Earth3
      - HadGEM3-GC31-MM
      - IPSL-CM6A-LR
      - MIROC6
      - MPI-ESM1-2-HR
      - NorCPM1

subset:
  full:
    name: full
    best_n:
    worst_n:
    projects:
    models:
  best_n:
    name: best_n
    best_n: 20
  cmip5:
    name: cmip5
    projects: cmip5
  cmip6:
    name: cmip6
    projects: cmip6

aggregation_period:
  yr2to9:
    name: yr2to9
    lead_time: "2:9"
    study_period: "1960:2005"
    observed: TRUE
    hindcast: TRUE
    lag: FALSE
  yr2to9_lag:
    name: yr2to9_lag
    lead_time: "2:9"
    study_period: "1960:2005"
    observed: FALSE
    hindcast: TRUE
    lag: TRUE
    n_lag: 4
  yr2to5_lag:
    name: yr2to5_lag
    error_name: yr2to9_lag
    error_season: DJFM
    lead_time: "2:5"
    study_period: "1960:2005"
    observed: FALSE
    hindcast: TRUE
    lag: TRUE
    n_lag: 4
  yr2to5:
    name: yr2to5
    error_name: yr2to9_lag
    error_season: DJFM
    lead_time: "2:5"
    study_period: "1960:2005"
    observed: TRUE
    hindcast: TRUE
    lag: FALSE
  yr6to9_lag:
    name: yr6to9_lag
    error_name: yr2to9_lag
    error_season: DJFM
    lead_time: "6:9"
    study_period: "1960:2005"
    observed: FALSE
    hindcast: TRUE
    lag: TRUE
    n_lag: 4
  yr6to9:
    name: yr6to9
    error_name: yr2to9_lag
    error_season: DJFM
    lead_time: "6:9"
    study_period: "1960:2005"
    observed: TRUE
    hindcast: TRUE
    lag: FALSE
  yr2:
    name: yr2
    error_name: yr2to9_lag
    error_season: DJFM
    lead_time: "2"
    study_period: "1960:2005"
    observed: TRUE
    hindcast: TRUE
    lag: FALSE

modelling:
  hindcast_Q95:
    name: hindcast_Q95
    input_dataset: hindcast-analysis
    predictand: Q_95
    model_family: GA
    study_period: 1960:2005
    formulas:
      P: Q ~ european_precip
      P_T: Q ~ european_precip + amv
      NAO: Q ~ nao
    subsets:
      - full
      - best_n
  observed_Q95:
    name: observed_Q95
    input_dataset: observed-analysis
    predictand: Q_95
    model_family: GA
    study_period: 1960:2005
    formulas:
      P: Q ~ european_precip
      P_T: Q ~ european_precip + amv
      NAO: Q ~ nao
    subsets:
      - observed
