---
input_data_root: /Users/simonmoulds/projects/decadal-flood-prediction/data-raw
output_data: results

observed_data:
  root: /Users/simonmoulds/projects/decadal-flood-prediction/data-raw
  giss:
    subdirectory: observed_data/GISS
  gpcc:
    subdirectory: observed_data/GPCC
  hadcrut4:
    subdirectory: observed_data/HadCRUT4
  hadslp2r:
    subdirectory: observed_data/HadSLP2r
  hadisst:
    subdirectory: observed_data/HadISST
  ncdc:
    subdirectory: observed_data/NCDC

ensemble_data:
  root: /Users/simonmoulds/projects/decadal-flood-prediction/data-raw
  cmip5:
    subdirectory:
      - esmvaltool_output/recipe_s20_cmip5_autogen_20221214_103843/
    grid_subdirectory:
      - esmvaltool_output/recipe_s20_grid_cmip5_autogen_20220622_133817
    models:
      - CanCM4
      - GFDL-CM2p1
      - HadCM3
      - MIROC5
      - MPI-ESM-LR
  cmip6:
    subdirectory:
      - esmvaltool_output/recipe_s20_cmip6_autogen_20221214_120531
      - ncar_prec_data/recipe1
    grid_subdirectory:
      - esmvaltool_output/recipe_s20_grid_cmip6_autogen_20220622_153338
    models:
      - CanESM5
      - CESM1-1-CAM5-CMIP5
      - EC-Earth3
      - HadGEM3-GC31-MM
      - IPSL-CM6A-LR
      - MIROC6
      - MPI-ESM1-2-HR
      - NorCPM1

aux_data:
  root: /Users/simonmoulds/projects/decadal-flood-prediction/data-raw
  camels:
    subdirectory: 8344e4f3-d2ea-44f5-8afa-86d2987543a9
  ukbn:
    subdirectory: UKBN

