name: conda_environment_base
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck
  - click
  - dask
  - iris
  - netCDF4
  - pandas
  - python=3.10
  - pip
  - pyarrow
  - tqdm
  - xarray
